# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Adam8enの8log
subtitle: ''
description: 你的孤独与月为伴，你的深情与星同归
keywords: AdamBen,Adam8en
author: Adam Ben
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
# permalink: :year/:month/:day/:title/
permalink: posts/:hash/	 # 我这里改成posts/:hash
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:Adam8en/Adam8en.github.io.git
  branch: master

lazyload:
  enable: false
  loadingImg: /img/loading.gif
  isSPA: false # optional

#看板娘
live2d:
  enable: true
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-shizuku    #模板目录，在node_modules里,自己选择
  display:
    position: left
    width: 200 
    height: 400
  mobile:
    show: false  #是否在手机进行显示


# mbti_card:
#   cdn: false
#   language: 'zh'
#   gender: 'male'
#   slide: true
#   layout: "about"
#   data:
#     'E-I': [40, 60]
#     'S-N': [22, 78]
#     'T-F': [22, 78]
#     'J-P': [53, 47]
#     'A-T': [54, 46]
#   color: ["#4298b4", "#e4ae3a", "#33a474", "#88619a", "#f25e62"]

# hexo-bangumi
bangumi: # 追番设置
  enable: true
  source: bili
  bgmInfoSource: 'bgmv0'
  path:
  vmid: 286749364
  title: '追番列表'
  quote: '生命不息，追番不止！'
  show: 1
  lazyload: false
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading: /img/friend_404.gif
  showMyComment: false
  pagination: false
  metaColor:
  color:
  webp:
  progress:
  progressBar:
  extraOrder:
  order: latest
  proxy:
    host: '代理host'
    port: '代理端口'
  extra_options:
    key: value
  coverMirror:
cinema: # 追剧设置
  enable: false
  path:
  vmid:
  title: '追剧列表'
  quote: '生命不息，追剧不止！'
  show: 1
  lazyload: true
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading:
  metaColor:
  color:
  webp:
  progress:
  progressBar:
  extraOrder:
  order:
  extra_options:
    key: value
  coverMirror:
game: # 游戏设置，仅支持source: bgmv0
  enable: true
  path: games/index.html
  source: bgmv0
  vmid: 919296
  title: '游戏列表'
  quote: '有的游戏给我带来短暂的快乐，有的游戏却悄然影响我的一生。'
  show: 2
  lazyload: false
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading: /img/friend_404.gif
  metaColor:
  color:
  webp:
  progress:
  progressBar:
  extraOrder:
  order: -score
  extra_options:
    key: value
  coverMirror:

#hexo-douban
douban:
  id: 283842719
  builtin: false
  dynamic: false
  item_per_page: 10
  meta_max_line: 4
  customize_layout: page
  swup: false
  book:
    path: books/index.html
    title: "书籍列表"
    quote: "我思故我在"
    actions: 
      - do
      - wish
      - collect
    option:
# movie:
#   path: movies/index.html
#   title: "This is my movie title"
#   quote: "This is my movie quote"
#   actions:
#     - do
#     - wish
#     - collect
#   option:
# game:
#   path: games/index.html
#   title: "This is my game title"
#   quote: "This is my game quote"
#   actions:
#     - do
#     - wish
#     - collect
#   option:
# song:
#   path: songs/index.html
#   title: "This is my song title"
#   quote: "This is my song quote"
#   actions:
#     - do
#     - wish
#     - collect
#   option:

# markdown:
#  plugins:
#    - plugin:
#      name: '@neilsustc/markdown-it-katex'
#      options:
#        strict: false

# markdown:
#   render:
#     html: true
#     xhtmlOut: false
#     breaks: true
#     linkify: true
#     typographer: true
#   plugins:
#   anchors:
#     level: 1
#     collisionSuffix: ''